### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by memoryskull** [CatalystCode/appinsights-on-premises#1]
Hi good day @c-w 
I am a graphic designer and I would like to contribute with the project
I can offer a logo that represents the project.
You can receive the logo without any commitment.
I want to contribute because I like to do it.
Thanks for your time.

Cheers!

**Comment by c-w** [comment]
Thanks for reaching out and for the offer @memoryskull. This would be a great addition to the project.

The official logo of AppInsights (and the related project Azure Monitor) are here:

![AppInsights logo](https://user-images.githubusercontent.com/1086421/61898450-5350e680-aee7-11e9-9ff6-42b836fb000f.png)

Perhaps this can act as an inspiration?

**Comment by c-w** [comment]
Going to resolve this due to inactivity. Feel free to reopen if you're still interested in tackling this. Thanks!
